const actionTypes = {
  SET_SORT_BY: 'SET_SORT_BY',
  SET_CATEGORY: 'SET_CATEGORY',
  SET_PIZZAS: 'SET_PIZZAS',
  SET_LOADING: 'SET_LOADING',
  ADD_PIZZA_TO_CART: 'ADD_PIZZA_TO_CART'
};

export default actionTypes;